var cnt=0;
console.log('hello');
cnt+=1;
var a = 10;
cnt+=1;
var b = 20;
cnt+=1;
var sum = a + b;
cnt+=1;
var product = a * b;
cnt+=1;
var division = b / a;
cnt+=1;
var max_val = (a > b) ? a : b;
cnt+=1;
var arr = [a, b, sum];
cnt+=1;
var obj = { x: a, y: b };
cnt+=1;
function add(x, y) { return x + y; }
cnt+=1;
var result = add(a, b);
cnt+=1;
var str1 = 'Hello';
cnt+=1;
var str2 = 'World';
cnt+=1;
var str3 = str1 + ' ' + str2;
cnt+=1;
var all_pass = (sum === 30) && (product === 200) && (division === 2) && (max_val === 20) && (arr.length === 3) && (arr[0] === 10) && (arr[1] === 20) && (arr[2] === 30) && (obj.x === 10) && (obj.y === 20) && (result === 30) && (str3 === 'Hello World');
all_pass ? cnt : 0;
